### ISSUE TITLE
Update sign in error message styling

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#2053]
When an error occurs on the sign in page

The styling for the error message doesn't match styling of other errors

<img width="1138" alt="Screenshot 2023-05-05 at 11 57 40 AM" src="https://user-images.githubusercontent.com/62242/236508365-9099caec-75d2-486a-9b40-f859a35b9603.png">

### Steps
- http://localhost:3000/en/auth/login
- enter test@test.com
- password `a`
- press submit  -- see error message

**Comment by samsadasivan** [comment]
For this alert, we will go with our general alert style, at the top of the page. I added a image of the three styles of alerts we currently have to associate to the app. 

🚩 🚩🚩 @timarney @srtalbot 
I wonder if this alert is styled this way because the sign-in flow is public facing, and the style would need to match the canada.ca brand and tone. Therefore, this alert would stay the same.. and if so, ill add it to the types of alerts we have

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/4045889b-a2a0-4872-8a92-037c6c68bd95)

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/12ba0bb9-5480-4f98-bf57-52693669e6d8)

**Comment by timarney** [comment]
Yes it's more of a public acing form error.
That said should 

1) we drop the X

2) Add an error heading
3) Make the rest of the text "non-bold" and add a link to support?


<img width="825" alt="Screenshot 2023-05-08 at 4 08 02 PM" src="https://user-images.githubusercontent.com/62242/236923380-00edd20a-ade1-4cd4-b288-03f8d7d302bc.png">

**Comment by samsadasivan** [comment]
Yes - that works perfectly Tim. Lets move forward with that

**Comment by samsadasivan** [comment]
![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/e607704f-67c8-4f21-bde7-f37d668774dc)

Pinged @anikbrazeau for a second look and to translate :)

**Comment by samsadasivan** [comment]
Ready for implementation ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/61534b4f-2f73-46b8-b43b-1346066e1d80)

**Comment by thiessenp-cds** [comment]
When this is ready for development, the task can be assigned to me. The work overlaps with another task I'm working on #1898

**Comment by thiessenp-cds** [comment]
Solved with PR https://github.com/cds-snc/platform-forms-client/pull/2080
