### ISSUE TITLE
As soon as we connect to a database, and the form is going from Draft to Publish -> empty the vault.

### ISSUE THREAD

**Issue by daine** [cds-snc/platform-forms-client#2337]
**User story:**
As a forms administrator
I need to clear all test responses as soon as I publish my form
So that I don't get an email reminding me to clear old test data

**Story context**
When users are testing their form, they are able to create test responses/test submissions using the "Preview" tab. These submissions are test data when the form is still in draft or unpublished.

**_Unresolved_**:
Question: How do we want to communicate this action to our users? See red text below:
<img width="1214" alt="Screenshot 2023-06-28 at 11 17 32 AM" src="https://github.com/cds-snc/platform-forms-client/assets/916044/4ebba39a-3cb1-495f-98d1-9da1318f7973">

1) I wonder if we could or should update the Responses tab for unpublished forms to something like "Preview responses" or "View Test Responses?

2) We can probably add a logic check if there are any responses and only show the navigation menu on the left (the Responses tab) if there are any. But thinking about this more, I think it's best left alone as is?

3) For messaging about responses, I wonder if we would want to do a logic check to only show the warning message? There's already one warning message on the screen and I wonder if a user will be more inclined to ignore warnings if there are too many of them

4) Is there a preferred design for displaying this new warning message?

**Comment by samsadasivan** [comment]
when I say UI ... I mean component haha 😅

**Comment by samsadasivan** [comment]
We changed the layout a bit for the proposed way of communicating _What you need to know before publishing_ 

Notes: 
- We decided to not make it a big alert and treated it similarly to the "Know your responsibilities" layout with the sign in history
- This component could be used for any guidance we want to add in the future on the right side. In the new layout (v2 navigation proposal) we can reassess the columns and make the right side smaller. 
- This layout scales, but not too long. This layout helps with todays issue, and perhaps 2 more items in the future. Beyond that, we should probably start to tackle the “Before you publish” items instead of making the list longer
- This is just a proposal for now, we can edit the content based on the product decision around test responses for published forms 
![image](https://github.com/cds-snc/platform-forms-client/assets/16671230/3826a7ce-21e2-44b4-99f9-d74f99a6c40d)

**Comment by samsadasivan** [comment]
Some logic, if its a bigger lift we can change the content. 

Notes: 
- Ideally, it would be great to have some logic between the two delivery methods to we can don’t have an alert for forms set to email delivery
- If this is a larger lift, we can change the content to state that this is just set for “the vault” ... we won’t use that name
![image](https://github.com/cds-snc/platform-forms-client/assets/16671230/0b6a3b4e-31c5-46e9-bfb8-67485093cbea)

**Comment by samsadasivan** [comment]
v2 Bilingual screens are available under /Proposed 
![image](https://github.com/cds-snc/platform-forms-client/assets/16671230/f39ed3a0-7414-4f4e-aeee-9dab5a43a0ad)
