### ISSUE TITLE
Product marketing site revamp

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2361]
Work in tandem with growth to update the content in preparation to PB launch.

https://docs.google.com/document/d/1IGqgZf9hyO6lA8eNUpLtMfqwgyBNvC3EB0hR09rKGh4/edit#heading=h.jzqc0lh3ctlp

**Comment by connorscarolyns** [comment]
link to feedback https://docs.google.com/document/d/1rpEBTX8nLxEZfv6YP4zqjGjinXJnS1tvgjshWaC0WEw/edit?usp=sharing

**Comment by Abi-Nada** [comment]
Don't need dev support, but will be needing design support.

**Comment by anikbrazeau** [comment]
Links: 

- [Growth strategy](https://docs.google.com/document/d/1sRgivFM-ng6rzft5lqb95IvoYdYjmBiBI06IoEdO7Ig/edit)
- [Marketing tactics](https://docs.google.com/spreadsheets/d/186C1qLxHZIhQP3neHXB1I8YEGgwpyy0_7_bHCFt8x90/edit#gid=0)

**Comment by jose-cds** [comment]
On top of my radar:
 
1. Incorporating your feedback 

I made a page in articles we can start incorporating edits to. We can start directly incorporating your feedback into it.


2. Adding 'Getting started with PB' page 

Public servants often ask what they need to do in order to create a PB form. They often ask what is required of them to use GC Forms and how the data is protected. The goals of this page is to provide clarity on what’s required to create PB forms so they can get started quickly.

Page to cover:
- How to create Protected B forms
- What is required to create an account
- Summary of their responsibilities when collecting PB data.
- How to export responses
- How we protect PB data

3. Update use cases on marketing page to add PB examples with corresponding visuals.

Could use some re-wording but narrowed them to 3:
- Simple intake form for a service
- Solicit updates from businesses
- Registration of interest form

**Comment by jose-cds** [comment]
Updated the strategy doc based on your feedback from our discussion yesterday. I'm going to update the [pitch deck ](https://docs.google.com/presentation/d/1IWfM9AbP1k152hf0g9BfQD2giohHYoxD/edit#slide=id.p1)as well once I check in with translations on how to best do it since they are in the process of translating the deck.

**Comment by anikbrazeau** [comment]
Organizing an activity to think through what people need to know and how to answer questions people might have, including how to get started

**Comment by anikbrazeau** [comment]
## Next steps

### Divide work on updates
- Anik = home
- Jose = features
- Carolyn = getting started

### Reconvening August 17, 2023

**Comment by jose-cds** [comment]
Preview of the features page here for the full revamp:

https://articles.alpha.canada.ca/forms-formulaires/features-page-edits

Preview of the interim page for Monday:

https://articles.alpha.canada.ca/forms-formulaires/interim-features

**Comment by jose-cds** [comment]
For review tomorrow:
- Getting started page. (https://articles.alpha.canada.ca/forms-formulaires/2022/02/21/hello-world/(opens in a new tab)) courtesy of @connorscarolyns 
- Features page (https://articles.alpha.canada.ca/forms-formulaires/features-page-edits)
- Home page (https://articles.alpha.canada.ca/forms-formulaires/front-page-edits/) courtesy of @anikbrazeau. Btw here's where I started tinkering with the home page. ^ We can transfer to the official one after.

To confirm tomorrow:
- What content can be translated and published ahead of Monday.
-  What content is being sent to translations for publishing after Monday.

Final prep ahead of Monday
- Add new visuals to the home page (waiting on brand)
- Ensure corresponding updates are also made in French.

**Comment by anikbrazeau** [comment]
## Where we're at

Mocking up all pages together in English and French in Figma: 
https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=2941%3A32785&mode=design&t=sFLaHKziazgtTMg1-1

(Based on proposed changes linked above)

**Comment by anikbrazeau** [comment]
# Lastest mock-ups (Aug 29, 2023)

## Home
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHhMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f044616cf8e3510b2cb91a12aa3c29707c0093a/image.png)

## Features
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDVMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bf7aa40b6257dfdf48f605903f789f7b5a31a5c/image.png)

## Why GC Forms
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUJMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6720842d574bd8466e4ba60478b4b87ac693460f/image.png)

## Get started 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUZMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--16b54308c1fc3c6861df4425afa335b4e84301cd/image.png)

## Templates
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU5MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7108eed5935a1e269164b1851f6d2bf16089cb90/image.png)

## Contact us
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWRMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--470f4ed01b2834808b9e16b41ca921024428c5a8/image.png)

**Comment by anikbrazeau** [comment]
## Update
- English pages in Figma reviewed by Lesley.
- French pages in Figma reviewed by Nicholas.
- Pages currently being built in GC Articles by Carolyn and others.

## Next steps
- Finalize the staging of all pages in Articles in EN and FR.
- Review of entire staged site by Ioana and visual design.

**Comment by jose-cds** [comment]
- Figma file shared with brand for review

**Comment by anikbrazeau** [comment]
Anik working on creating corresponding FR pages in Articles and providing bilingual alt text for all visuals.

**Comment by anikbrazeau** [comment]
SHIPPED! 🚀🎉 [Making small tweaks here and there to enhance/improve it but closing this for now, as complete]
https://gcdigital.slack.com/archives/C0117FN8G9K/p1695327594041359
