### ISSUE TITLE
Update Product Screens to Reference "Protected B"

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2370]
### User Story:

As a user, I want to be able to set "Protected B" as a data classification within the product, so that it correctly reflects the sensitivity of the information being gathered, and is delivered to the right place.

Tasks:
- Adjust Product Screens: Identify product screens that display or handle PB data
- Update Settings Menu

### Acceptance Criteria:
- [x] The Settings menu includes the option to select the data classification level "Protected B"
- [x] The response delivery method is adjusted based on the selected data classification level (blocks out email delivery for PB)
- [x] SLA and ToU reflect Protected B changes

**Comment by samsadasivan** [comment]
✅ _Protected B_ added to the drop down in the /Settings page (implemented)
✅ Designs were already crafted by Carolyn for changing the delivery method based on their classification selection (img attached) ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/ea427997-e37d-46eb-841a-576a9f147ca4) 
🟡 I still think there should be a way to "preview" or be reminded of your selection before you publish. Going to see where the best place for that is, since it won't be designed into the form output. Perhaps the publishing page

**Comment by samsadasivan** [comment]
Proposal for reiterating what classification was chosen before publishing: 
- adding some small bold text in the line before the checklist. ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/b65d6d74-7fd7-41be-b464-f5cce2c3826e)

Not a heavy lift on the UI front, but some logic would need to be added for this to work. This stretches beyond the checklist that is scoped - it is ok if it doesn't make it in this round.

**Comment by samsadasivan** [comment]
Content for the delivery method info-alert has changed - Pinged @anikbrazeau for extra look and support on bilingual content[Uploading... image.png]

**Comment by samsadasivan** [comment]
New alert: 
```
EN: PROTECTED B responses must be downloaded from GC Forms 
FR: Les réponses classifiées PROTÉGÉ B doivent être téléchargées de Formulaires GC
```

**Comment by anikbrazeau** [comment]
Done! ✅ 🚀
