### ISSUE TITLE
Add call back from Notify on email status

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#242]
Currently we accept the 2xx response call to the Notify API as success that the email has been sent.  Unfortunately there could be errors once Notify is invoked and the GCForms platform would not be notified and the submission would be lost.

Notify does provide a call back url that signals the email has been successfully sent.  The GCForms platform should not delete the form submission from memory until the unique call back identifier has been invoked.

GCForms - > Notify API -> Process sending email -> GCForms API -> Remove submission from memory

Possible solution:
Reliability Queue -> Submission Processing -> Set submission status to processing -> Create uuid -> Send to Notify API with uuid as parameter in callback url -> Notify API -> Process sending email -> GCForms API  - > Remove entry from Processing Table

**Comment by craigzour** [comment]
What do you think about keeping the submission in the Reliability table until we get a callback from GCNotify? Our GC Forms new callback path will then delete the submission from the Reliability table (if success) or send a message to SQS (if failure) in order to trigger a new Reliability lambda execution on the same submissionID?
Since we already pass the submissionID as reference when calling the GCNotify API we can use it when it gets back to us in the callback payload to delete the right submission in the Reliability table.

Something that I am not sure how we want to deal with is the fact that we could get multiple callback from GCNotify for the same `sendEmail` request with a success and then some kind of "failure" (if I properly understood). See https://documentation.notification.canada.ca/en/callbacks.html#message-delivery-receipts (Multiple callbacks for a notification yellow text box).

**Comment by Moro-Code** [comment]
I really like this idea @craigzour . I think a potential solution to the multiple callback problem is instead of deleting responses right away we move them to a holding table that deletes after a certain amount of time (say 24h). If another callback comes with a failure the response can be put back into the Reliability table (via the callback api route  we will create) and an SQS message created to deliver that again through the reliability queue. 

There are a couple of things that we potentially may need to think about as well 

1. What happens if we get no callback ? Will the message be left in the Reliability table forever
2. For these statuses  permanent-failure, temporary-failure or technical-failure we need to identify which ones mean the email will not be delivered no matter what we do (i.e. the inbox is closed or something ). Do we potentially count how many times we've tried and give up after a couple of tries ?

**Comment by craigzour** [comment]
Currently drafting a Design Doc https://docs.google.com/document/d/1XXtqmSeQXQRdklpz4FmpUdagKgr6new67633OsyHmzg
