### ISSUE TITLE
Usability testing of Download aggregated responses and Delete flows

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2788]
Early prototype testing

- [x] Research plan
- [x] Create testable prototypes
- [x] Recruitment
- [x] Facilitation Guides
- [x] Finding report

**Comment by jose-cds** [comment]
Recruitments list for you. It's a start we can look at adding more if need be. I separated it into 4 segments:
- People interested in dynamic fields
- People interested in testing exporting as a CSV
-  People who are not using GC Forms because we don't have exporting capabilities. 
-  People interested in testing opportunities.

https://docs.google.com/spreadsheets/d/1Z7zlL6FEqG-mzK-7v0kQbFAmT2a1z5DNZUvgplxC4qE/edit?usp=sharing

**Comment by Abi-Nada** [comment]
Reached out to contacts in the recruitment list under "people interested in dynamic rows". So far will be scheduling 2 sessions (for 3 participants) next week.
