### ISSUE TITLE
Left Navigation update

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3058]
[Draft card]

- New grid style for desktop
- Iconography sizes 24x24
- Open/Close (or Tip/Label, consider accessibility)

**Comment by samsadasivan** [comment]
PROPOSAL 

- Left navigation is a sticky nav that does not expand, but just shows the icons of each step in the form building stage.
- Notes:
- When you are on the page selected, the icon will show its active with a span of 60px in indigo-700, the icon will become slate-50
- There is no space between icons because of this span
- When you hover or focus on any of the nav items, a tool tip will appear with the label of the nav in FR or EN
- All icons have been adjusted to a frame of 32 pxs (icon + padding) since they are all different shapes

**Comment by samsadasivan** [comment]
<img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af89fa87f6f5e1efad819c5d56768e6f45d9ed50/image.png" alt="image.png" />
<img width="1018" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9hQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e867e155d753c455db0eaf4d71fa32dc1ce99631/image.png" alt="image.png" />
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3aed66e8e8a1eb9f2ca52c696002b7fe2416f93e/image.png" alt="image.png" />
