### ISSUE TITLE
"Tree view"/ Sections in Right Panel

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3063]
### Description

Allow users to add and rearrange sections within a form

### Acceptance Criteria:
- [x] Users can add new sections to a form
- [x] Users can rearrange the order of sections via drag-and-drop
- [x] Users can rearrange the order of questions via drag-and-drop
- [ ] Removing sections
- [ ] Privacy policy, intro and confirmation: do they remain in the tree view?
- [ ] Handle re/autoFlow of sections when adding or rearranging

**Comment by samsadasivan** [comment]
Default state: 
- Panel is open when navigating to /Edit 
- Essential elements are in premade groups that cannot be moved (locked groups) 
- Essential groups are pre-labeled but can be edited (language interface toggle will not change the names of the groups as they are populated by the user like form file name) 
- Branding and Classification settings will stay in its current component for now and can be revisited in the future 



<img width="1151" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2EwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a866bcd55f018de6a063fcd463042084f914fab/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Adding a question to a group: 
- You can only add a question to a group via the button in the centre next to the cards, using the add element modal. 
- 
<img width="1179" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzIwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa479c769261c592ee6e082565fce687fd9ac9be/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Add a new group to a form: 
- TERM CHANGE: Rename "Group" to "Section"
- Select "New Section" 
- New closed section appears with an editable input field, default text is "Section". If sections are made with the same name, then "copy" will follow. Example "Section copy copy copy" 
- "enter" or click off will save. Similar interaction to naming form file in the header 
- Truncates (...) after 45 Characters 
- Built in restriction: Every section will have a H2 header. This would ideally be H1 but since we don't have pagination or breadcrumbs at this time for the form output, we still need to let users know what form they are on and the section they are on 

<img width="1120" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHkwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a24bf43fc60d130c12303c52308621d362e64ea2/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Rename a section: 
- In order to rename a section, users must open the section -> double click the group name and an input field will appear to change the name 
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0MwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cee1d97f96916cf815a118e1e13bd05d617f4b66/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Reorder a group: 
- You need to make sure the group you want to move is closed. If all groups are closed, the centre stage will show the the content of the last group opened 
- On hover, a drag indicator will appear on the group 
- Drag fixed on a vertical plane, dotted border, with a 2 px line to indicate where the group will be dropped

**Comment by samsadasivan** [comment]
**Form output**

Blocker: No stepper for now as it will add more confusion if you skip steps based on the answer you submit 

Review page is crucial, we cannot have the groups functionality without a way to double check your answers 

<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL08wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dadf6543781263cd31ae614ba7fa4031ad70179/image.png" alt="image.png" />

<img width="801" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1MwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1563b1ec764a7da5d8b27379ecd39c60af45a67/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Work lived under Dynamic fields + Grouping questions/ Page: [Right panel (dev test)](https://www.figma.com/file/2bmknDRpZXN3lwqhs7mqNH/Dynamic-fields-%2B-Grouping-questions?type=design&node-id=1443-9511&mode=design)

**Comment by samsadasivan** [comment]
**UPDATE:** 

So that we don't confuse users with our right panel update, lets keep "Questions" and "Translations" as labels for the views the same. We can update the content when we learn more about how folks are interacting with the panel

**Comment by anikbrazeau** [comment]
https://www.figma.com/file/2bmknDRpZXN3lwqhs7mqNH/Dynamic-fields-%2B-Grouping-questions?type=design&node-id=1589-16096&mode=design&t=pYZ45CStZ1H2kpWe-0
