### ISSUE TITLE
Responses table pagination not going to next "page"

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3162]
## Description
Trying to paginate beyond the first 150 responses fails to paginate

## Steps to reproduce
1. Go to a form with over 150 responses. Responses 1-150 are shown.
2. Click on the "Next" link/button in the responses table
3. The original responses 1-150 are shown

## Expected behaviour
Clicking next shows the response 150-*

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/107579368/ada8b214-1e2b-481d-a718-c74d0f771e8f

**Comment by dsamojlenko** [comment]
The problem here is the language middleware - the links for the pagination don't include the en/fr prefix, so the middleware fixes this, but doesn't append the query params needed for pagination.

So we can attack this one of two ways:
- prepend the language prefix on the pagination links
- adjust the middleware to preserve the query params

I believe the second option is preferable, have dug into it a bit, but haven't been able to figure out how to access the query params from the middleware. `req.nextUrl.searchParams` always seems to be empty.

Will continue to investigate.

**Comment by dsamojlenko** [comment]
actually, req.nextUrl.searchParams wasn't empty, just need to serialize it with `req.nextUrl.searchParams.toString()`

**Comment by dsamojlenko** [comment]
https://github.com/cds-snc/platform-forms-client/pull/3213

**Comment by bryan-robitaille** [comment]
While it is easier to adjust the middleware, from an optimization standpoint, we're slowing down the page rendering because every pagination link will be responded to with a 3xx response that the browser needs to make another round-trip request to the server.

**Comment by bryan-robitaille** [comment]
I think you're right though that there are 2 options.  I haven't tested the rewrite() instead of redirect in the middleware.  The other option is to ensure that we always include the locale in all our links.
Either way we'll need to standardize across the code base how we want to link to other pages.

**Comment by timarney** [comment]
@dsamojlenko this is fixed now ya?

Partially via https://github.com/cds-snc/platform-forms-client/pull/3218

**Comment by thiessenp-cds** [comment]
IMO I prefer including the locale in links for simplicity and because we haven't tested rewrite() yet. But as mentioned sounds like either option should be standardized across all links and that's probably best done in a separate PR.

Works as expected. Closing with the note above
