### ISSUE TITLE
repetitive console log noises "{time: 1710877247722, level: 30, msg: 'Form Timer useEffect - timer enabled'} ..

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3365]
<img width="1587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFR6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0fd44abafd7d9146b72068a14eb97709e0a9691/image.png" alt="image.png" />

Form used: https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/fr/id/clpsy56bk000mvq83k8pyyrxa

**Comment by thiessenp-cds** [comment]
It looks like the console message is by design to update for each timer tick. Though I don't really see the value in the log message. 
@bryan-robitaille would there be any loss of useful logging info if I removed the related log message?
![Screenshot 2024-03-21 at 1 34 56 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/ad695d3f-2f1d-40d2-a40b-1d9d5b34bb98)

**Comment by thiessenp-cds** [comment]
Completed in related PR
