### ISSUE TITLE
Hint text for type-ahead pre-populates translation in English

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3371]
## Description
When adding a "Type-ahead" question and going to the Translate tab, the hint-text prepopulates as English on the French side.

## Steps to reproduce
1. Add a "type-ahead" question in English
2. Go to Translations
3. See error in the "French" section

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
The hint text should appear in French, for the French section

## Screenshots or videos
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTMyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5411208b13da071daeda64d389b7d094c837a45/Screenshot%202024-03-20%20at%208.47.50%E2%80%AFAM.png" alt="Screenshot 2024-03-20 at 8.47.50 AM.png" />

**Comment by Abi-Nada** [comment]
This also happens to adding the "Other" input field (conditional logic)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekQyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a2f58fa4cb57d31b7f07396acd4fa30d8d44a3e/Screenshot%202024-03-20%20at%208.51.07%E2%80%AFAM.png" alt="Screenshot 2024-03-20 at 8.51.07 AM.png" />

**Comment by dsamojlenko** [comment]
Noting that this is happening due to a bug in the new i18n client that affects client-side `t()` functions that attempt to force a language (ie, passes a `{ lng: "fr/en" }` prop)

Fortunately we don't rely on this function too much client side (we do rely on forcing a language extensively for our response downloads but they all render server-side).

To address for this particular case, creating a server action to retrieve the translations, but we may want to look more closely at the i18n client later.

WIP here: https://github.com/cds-snc/platform-forms-client/pull/3379

**Comment by dsamojlenko** [comment]
That PR has been merged, this should be fixed now.

**Comment by timarney** [comment]
Assigning to @Abi-Nada to confirm the fix.

**Comment by Abi-Nada** [comment]
Can confirm that the issue no longer persists! Thanks folks!
