### ISSUE TITLE
Add space before colon in French ( :)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3400]
## Description
In the email delivered with responses, add a space before the colon for the submission date and submission ID.

Date de soumission` `: 2024-03-21T19:54:30.022Z
ID` `: 83664126-0ea1-43dc-a4b9-bc5d26c56048

## Steps to reproduce
1. Set response delivery to email for a draft form
2. Submit a test response
3. Check the bottom of the response email

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App Router PR
- **Language**: French
- **Viewport**: tablet

## Expected behaviour
French grammar/punctuation rules

## Screenshots or videos
<img width="1428" alt="Screenshot 2024-03-21 at 3 55 09 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/2185ac68-b88c-4741-b7ae-90a81070acc3">

**Comment by anikbrazeau** [comment]
We might also want to consider flipping the logo for the French responses to have "Gouvernement du Canada" in French first?

**Comment by wmoussa-gc** [comment]
Et voila:

<img width="1035" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31fb6313568b4e9a6ae3fcb957d3b01649924b55/image.png" alt="image.png" />

But since we're using the Notify template to send the email with the GC brand, Notify doesn't allow switching the header for the same "service." Therefore, the solution would be to create a new Notify service and a set of templates to incorporate the new French branding logo.

Slack thread: https://gcdigital.slack.com/archives/C03FA4DJCCU/p1711392858214069 

cc @Abi-Nada @srtalbot

**Comment by anikbrazeau** [comment]
Indeed fixed! Thanks Wissam!

@Abi-Nada created new issue to capture branding: #3429
