### ISSUE TITLE
Page title and Sign-off button not appearing

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3502]
## Description
Once a response is downloaded, users are directed to the downloaded tab, where they need to sign-off on responses. The sign-off button is missing. The page needs to be refreshed to get it to appear.

## Steps to reproduce
1. Go to 'new responses'
2. Click on 'download selected'
3. Got to "downloaded" tab
4. See no button to sign-off on responses

## Details
- **Browser**: (Chrome)
- **Operating system**: (Mac)
- **Environment**: (PR)
- **Language**: (English)
- **Viewport**: (full screen)

## Expected behaviour
After I download a response and click on the "downloaded" tab, I should see the "sign off" button. The missing text and button will appear if I refresh the page.

## Screenshots or videos
<img width="1090" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99c73fd61f9895835b0a1b8836d082e1885bc465/image.png" alt="image.png" />

**Comment by dsamojlenko** [comment]
Believe this is fixed in this PR: https://github.com/cds-snc/platform-forms-client/pull/3519
...as mentioned there, it's a bit hard to recreate as it's related to server rendering and page cache. But I moved the TitleAndDescription component in question out of a server rendered Layout down to a client rendered Responses component. I believe this should fix the issue.

**Comment by timarney** [comment]
@connorscarolyns can you re-test when you get a chance the PR Dave mentioned has been merged.

**Comment by connorscarolyns** [comment]
Looks ok to me now

**Comment by Abi-Nada** [comment]
Closing as issue no longer persists :)
