### ISSUE TITLE
V1 - Create Infrastructure for API Server

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#3946]
depends on: #3944

**Comment by patheard** [comment]
Rough planning for API infrastructure:

## ECS
Add a new `form-api` service to the existing `Forms` cluster.  This will allow the API to scale independently with load, but still be logically grouped with the `form-viewer` service.

The `form-api` service will be in the private subnets and have security groups that allow it access to the Forms RDS cluster and the internet.  Additionally, IAM policies will be created to allow the `form-api` access to all required AWS resources (e.g. DynamoDB, S3, CloudWatch, etc).

## Load balancer
Use the existing `form-viewer` LB and setup [host based routing rules](https://aws.amazon.com/blogs/aws/new-host-based-routing-support-for-aws-application-load-balancers/) so that requests to `api.forms-formulaires.alpha.canada.ca` go to the `form-api` ECS service, while requests to `forms-formulaires.alpha.canada.ca` are sent to the `form-viewer` ECS service.
1. ⚠️ Consideration: the API and form viewer would need to share the same WAF ACL.
2. ⚠️ Consideration: research is needed to determine if sharing the load balancer could lead to performance issues.

## Route53
A new `api.forms-formulaires.alpha.canada.ca` record will be created pointing to the `form-viewer` load balancer. 

## ACM
The existing `forms-formulaires.alpha.canada.ca` certificate will be updated with a subject alternative name of `api.forms-formulaires.alpha.canada.ca`

## CloudWatch
Alarms will be created to monitor the API for:

1. High ECS resource usage.
2. API errors.

**Comment by patheard** [comment]
Terraform for the infrastructure will be created in `cds-snc/forms-terraform`.

**Comment by patheard** [comment]
Continuing to work on the Terraform for this in:
- https://github.com/cds-snc/forms-terraform/pull/736

One minor stumbling block is that if I update the main certificates `Subject Alternative Names`, it will force a re-issue of the cert, which would cause downtime if we didn't do anything.

I'm going to try the following:
1. Add an additional cert to the load balancer listener using an [`aws_lb_listener_certificate` resources](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate.html).
1. If that fails, look at requesting a new certificate and then only switching the load balancer and CloudFront to that cert once it has been validated and is available.
1. And if that fails, we'll fallback to just adding a new load balancer for the API.

**Comment by patheard** [comment]
API load balancer target is now responding with a fixed response to:
https://api.forms-staging.cdssandbox.xyz/

Form viewer still works as expected, with the next steps being:
- Manually build and push an API `hello world` docker image to the ECR in Staging.
- Update the Staging TF workflows to plan and apply the new API ECS service.
- Update the WAF ACL to allow the API paths.

**Comment by patheard** [comment]
API is now running in a `form-api` service and connected through the load balancer:
https://api.forms-staging.cdssandbox.xyz/status

**Comment by patheard** [comment]
New CloudWatch alarms are now in Staging:


![Image](https://github.com/user-attachments/assets/3b680ba1-f239-4167-b66a-aa0a17a19cdd)
