### ISSUE TITLE
Form validation does not work on IE11

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#399]
Form appears to submit and bypass any sort of validation on IE11

https://images.zenhubusercontent.com/315708034/7ec3a044-68dd-40cd-b133-23f96defc0eb/screen_recording_2021_08_26_at_12_48_01_pm.mov

**Comment by craigzour** [comment]
Linked to #394

**Comment by craigzour** [comment]
After spending time trying to figure out why the file upload component was not working on IE 11 I decided to take a different approach and started modifying the code in order to narrow down the root cause. By doing that I found a "solution" (probably not something we will move forward with) that fixed both the file upload component issue as well as the form validation one. 

The two issues appears to be connected and according to my findings it could be mostly related to the `next-auth` library.

Here is how you can make the forms work on IE 11:
* [_app.js](https://github.com/cds-snc/platform-forms-client/blob/main/pages/_app.js#L15) line 15 and 19
  * Remove `<Provider>` component
* [AdminNav.tsx](https://github.com/cds-snc/platform-forms-client/blob/main/components/globals/AdminNav.tsx#L40) line 40
  * Remove `signOut()` from `onClick` event
* [dataLayer.tsx](https://github.com/cds-snc/platform-forms-client/blob/main/lib/dataLayer.tsx#L465) line 465 and 660
  * Move both `_submitToAPI`and `submitToAPI` declarations in a different file
