### ISSUE TITLE
Contrast issue with secondary buttons in Articles site

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4043]
## Description
On the marketing website, not sure what happened, but the secondary buttons have a blue background rather than a white background? 

## Steps to reproduce
1. Go to https://articles.alpha.canada.ca/forms-formulaires/templates/
2. Scroll down to the form template options --> Preview link

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Prod
- **Language**: Both

## Expected behaviour
Secondary button white background similar to https://design-system.alpha.canada.ca/en/components/button/

## Screenshots or videos

<img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUgyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba12ee20fa2063c311cfd3f0fb5292c1cc656ccf/Screenshot%202024-07-19%20at%203.44.25%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 3.44.25 PM.png" />

<img width="1189" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUwyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a323321fc3a9df1d382446dd877fb4a1f64b5134/Screenshot%202024-07-19%20at%203.44.36%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 3.44.36 PM.png" />

**Comment by patheard** [comment]
Contrast issue with the buttons have been fixed on the English/French pages by adding the following two CSS classes:
```
has-background has-white-background-color
```

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmoyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--078bed174e3953576be32ba0eca09b87d3c1f2fa/image.png" alt="image.png" />


I also checked the rest of the marketing site and did not see any other buttons with the same contrast issue.  This was most likely due to the WordPress 6.6 release yesterday morning.

**Comment by anikbrazeau** [comment]
Fixed! Thanks Pat!
