### ISSUE TITLE
Putting a limit on open text fields

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4175]
### User Story
As a user of GC Forms,
I want a character limit on open text fields,
so that I can ensure my data is submitted successfully without causing payload or database issues.

As a developer on GC Forms,
I want to enforce a character limit on open text fields,
so that we can mitigate potential attack vectors.

### Description
This card stems from [#incident-2024-07-17-failed-form-submission-through-email-delivery](https://gcdigital.slack.com/archives/C07CPN1M938). We're seeing users add "Resume" open-text questions to their forms, and end users input 70 - 200KB of data. Notify has a **50k** limit, so if a form is email-delivery based and the submission is above the 50k limit, it gets sent to our deadletter queue.

As an immediate mitigation strategy, we need to put a character limit on open text fields.

### Acceptance Criteria:
- [ ] design input on how to let users know about this limit
- [ ] implementation of limit
- [ ] load testing to validate it works

**Comment by anikbrazeau** [comment]
This came up in our support sync yesterday.

Might a maximum limit of 10,000 characters (~1,600 words or 3.5 pages single-spaced) make sense for this?

**Comment by thiessenp-cds** [comment]
@Abi-Nada  from our sprint planning, I think we agreed to limit the scope of this fix to only assigning a maximum character count to individual text fields? (not a total response)

**Comment by thiessenp-cds** [comment]
@Abi-Nada / @timarney for applying the character check on "open text fields". I'm thinking that would be any form element that is either an input element or a textarea element?

**Comment by Abi-Nada** [comment]
Hi @thiessenp-cds ! Anik raised a related issue in [3111](https://github.com/cds-snc/platform-forms-client/issues/3111), and outlined expected behaviour:

**Short answer** ==> should have character limit rule option
**Long answer** ==> should have character limit rule option
Radio buttons ==> should NOT have character limit rule option
Checkboxes ==> should NOT have character limit rule option
Dropdown list ==> should NOT have character limit rule option
Attestation ==> should NOT have character limit rule option

**Comment by thiessenp-cds** [comment]
We could put different character limits on just the short and long answer fields. Though if this also related to a security concern, I would think all form inputs would have a maximum character length?

**Comment by thiessenp-cds** [comment]
The reason I'm thinking all inputs is that a user and edit the DOM of e.g. a checkbox and update the DOM value with whatever length of characters for the checkbox. So if we have a sort of global catch-all max character length for all inputs, there is no way to get around this (client side).

We could then add max character limits that override the the global character limit to specific inputs, like the short answer and long answer?

**Comment by anikbrazeau** [comment]
**Summary:**

- Problem is relevant for form submissions that get delivered by email with more than 50,000 characters. These end up in GC Notify's dead letter queue.
- Ideally, this problem submitting the response would be invisible to the end user filling out a form as it is related to the delivery method constraints rather than their response content.
- To mitigate issue, we can put a maximum character limit on individual fields that include `text area` aka "long answer".
- With a limit on "long answer" we may also want to consider a maximum character length for `text input` aka "short answer" as well as preset elements that use this component: "full name", "individual names" (first name, middle name, last name), "contact" (phone number, email), "address" (street address, city, province, postal code), "number", "date".
- We will need to figure out what to do and communicate for a scenario where a form filler adds more than the total/global number of characters that can be submitted (Option A: change email method to download method, Option B: reveal an error message that the response is too big / has too many characters, Option C: ?).

**Comment by thiessenp-cds** [comment]
Here is a flowchart that may help describe what I'm thinking. The global max would be a variable named something like `allFieldsMaxCharacters` and I think making it an admin setting would handy for future tweaks.

![Screenshot 2024-08-28 at 9 13 49 AM](https://github.com/user-attachments/assets/5f8f6b79-5bf5-4277-88a4-250d7c1e5f8c)

**Comment by thiessenp-cds** [comment]
There is also [the issue (#3111 )](https://github.com/cds-snc/platform-forms-client/issues/3111) of some form elements showing an option for "custom" max characters that should not be. I think this is separate from the above idea. But this issue can also be solved in this ticket/PR.

**Comment by anikbrazeau** [comment]
Decision after discussion: 

> Focus on max character length **per field** only for now :)

**Comment by thiessenp-cds** [comment]
From our quick talk in standup. 
We decided to use a hardcoded value for `inputMaxCharacters` instead of an Admin setting. One issue with the Admin setting is that an admin could set the value to 0 or another unintended amount and either "break" forms or open an attack vector.
Also some potential iteration on limiting text fields:
1. hard coded limit (current)
2. move limit to an admin setting
3. expand the admin setting to limits by delivery type (so a max for email, vault,..) and use in the app as a new formConfig

**Comment by thiessenp-cds** [comment]
Note that issue #3111 should be fixed in Dave's upcoming PR #4053
