### ISSUE TITLE
Standardize width settings and styling amongst all components

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#479]
I'm noticing that Checkbox and Radio button are the only ones that handle width differently than all the other components. I'm wondering if it would be a good time then to implement more standardized width settings for all of the components so we don't run into this issue in the future again. I can see that if we add a RichText box that it would also now be out of sync with checkbox, radio, and richText.

**Comment by connorscarolyns** [comment]
Width of paragraph text is odd on mobile devices, please connect with me when this issue is in progress to ensure we are adopting the right strategy for dealing with line lengths and text widths on all devices. ![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/0e86ad92-c635-4f5c-a859-08aafff50d2e)
